default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: game_api_development

test:
  <<: *default
  database: game_api_test

## set these environment variables on your prod server
#production:
#  <<: *defaults
#  host: <%= ENV['MONGO_HOST'] %>
#  port: <%= ENV['MONGO_PORT'] %>
#  database: <%= ENV['MONGO_DB'] %>
#  username: <%= ENV['MONGO_USERNAME'] %>
#  password: <%= ENV['MONGO_PASSWORD'] %>
